# Generated by Django 4.0.3 on 2022-03-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
    ]
