# Generated by Django 4.0.3 on 2022-03-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapi', '0002_alter_book_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.FloatField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='No title', max_length=7000),
        ),
    ]
