# Generated by Django 4.0.3 on 2022-03-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('title', models.CharField(default='No title', max_length=3000)),
                ('authors', models.JSONField(blank=True, max_length=3000, null=True)),
                ('published_date', models.CharField(blank=True, max_length=30, null=True)),
                ('categories', models.JSONField(blank=True, max_length=3000, null=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('ratings_count', models.IntegerField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, max_length=20000, null=True)),
            ],
        ),
    ]
