# Generated by Django 4.0.3 on 2022-03-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_average_rating_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ratings_count',
            field=models.IntegerField(blank=True, max_length=3000, null=True),
        ),
    ]
